// Code generated by goctl. DO NOT EDIT.
// Source: ch14_go_zero_rpc.proto

package server

import (
	"context"

	"go-base-learning/ch14_go_zero_rpc/ch14_go_zero_rpc"
	"go-base-learning/ch14_go_zero_rpc/internal/logic"
	"go-base-learning/ch14_go_zero_rpc/internal/svc"
)

type Ch14GoZeroRpcServer struct {
	svcCtx *svc.ServiceContext
	ch14_go_zero_rpc.UnimplementedCh14GoZeroRpcServer
}

func NewCh14GoZeroRpcServer(svcCtx *svc.ServiceContext) *Ch14GoZeroRpcServer {
	return &Ch14GoZeroRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *Ch14GoZeroRpcServer) Ping(ctx context.Context, in *ch14_go_zero_rpc.Request) (*ch14_go_zero_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
