// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: student.proto

package endpoint

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Student with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Student) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	// no validation rules for Classes

	// no validation rules for Grade

	return nil
}

// StudentValidationError is the validation error returned by Student.Validate
// if the designated constraints aren't met.
type StudentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StudentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StudentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StudentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StudentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StudentValidationError) ErrorName() string { return "StudentValidationError" }

// Error satisfies the builtin error interface
func (e StudentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStudent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StudentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StudentValidationError{}

// Validate checks the field values on StudentRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *StudentRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	return nil
}

// StudentRequestValidationError is the validation error returned by
// StudentRequest.Validate if the designated constraints aren't met.
type StudentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StudentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StudentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StudentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StudentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StudentRequestValidationError) ErrorName() string { return "StudentRequestValidationError" }

// Error satisfies the builtin error interface
func (e StudentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStudentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StudentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StudentRequestValidationError{}
