// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: ch14_go_zero_rpc.proto

package ch14_go_zero_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Ch14GoZeroRpc_Ping_FullMethodName = "/ch14_go_zero_rpc.Ch14_go_zero_rpc/Ping"
)

// Ch14GoZeroRpcClient is the client API for Ch14GoZeroRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Ch14GoZeroRpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type ch14GoZeroRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewCh14GoZeroRpcClient(cc grpc.ClientConnInterface) Ch14GoZeroRpcClient {
	return &ch14GoZeroRpcClient{cc}
}

func (c *ch14GoZeroRpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Ch14GoZeroRpc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Ch14GoZeroRpcServer is the server API for Ch14GoZeroRpc service.
// All implementations must embed UnimplementedCh14GoZeroRpcServer
// for forward compatibility
type Ch14GoZeroRpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedCh14GoZeroRpcServer()
}

// UnimplementedCh14GoZeroRpcServer must be embedded to have forward compatible implementations.
type UnimplementedCh14GoZeroRpcServer struct {
}

func (UnimplementedCh14GoZeroRpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCh14GoZeroRpcServer) mustEmbedUnimplementedCh14GoZeroRpcServer() {}

// UnsafeCh14GoZeroRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Ch14GoZeroRpcServer will
// result in compilation errors.
type UnsafeCh14GoZeroRpcServer interface {
	mustEmbedUnimplementedCh14GoZeroRpcServer()
}

func RegisterCh14GoZeroRpcServer(s grpc.ServiceRegistrar, srv Ch14GoZeroRpcServer) {
	s.RegisterService(&Ch14GoZeroRpc_ServiceDesc, srv)
}

func _Ch14GoZeroRpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Ch14GoZeroRpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ch14GoZeroRpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Ch14GoZeroRpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Ch14GoZeroRpc_ServiceDesc is the grpc.ServiceDesc for Ch14GoZeroRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ch14GoZeroRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ch14_go_zero_rpc.Ch14_go_zero_rpc",
	HandlerType: (*Ch14GoZeroRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Ch14GoZeroRpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ch14_go_zero_rpc.proto",
}
