// Code generated by goctl. DO NOT EDIT.
// Source: ch14_go_zero_rpc.proto

package ch14gozerorpcclient

import (
	"context"

	"go-base-learning/ch14_go_zero_rpc/ch14_go_zero_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = ch14_go_zero_rpc.Request
	Response = ch14_go_zero_rpc.Response

	Ch14GoZeroRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultCh14GoZeroRpc struct {
		cli zrpc.Client
	}
)

func NewCh14GoZeroRpc(cli zrpc.Client) Ch14GoZeroRpc {
	return &defaultCh14GoZeroRpc{
		cli: cli,
	}
}

func (m *defaultCh14GoZeroRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := ch14_go_zero_rpc.NewCh14GoZeroRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
